# Generated by Django 4.2.21 on 2026-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuildcomponent',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='fan_headers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Motherboard: fan headers', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fan_mounts',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Case: fan mounting positions', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fan_size',
            field=models.CharField(blank=True, help_text='Fan: size in mm, e.g. 120. Case: supported sizes, e.g. 120,140', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='m2_slots',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Motherboard: M.2 slots', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_memory_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Motherboard: max supported RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_capacity_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Memory: total kit capacity in GB', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_modules',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Memory: sticks per kit', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_slots',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Motherboard: DIMM slots', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sata_ports',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Motherboard: SATA ports', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_interface',
            field=models.CharField(blank=True, choices=[('M.2', 'M.2'), ('SATA', 'SATA')], help_text='Storage: M.2 or SATA', max_length=10),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='slot_key',
            field=models.CharField(blank=True, choices=[('cpu', 'CPU'), ('mobo', 'Motherboard'), ('ram', 'Memory'), ('gpu', 'Graphics Card'), ('psu', 'Power Supply'), ('storage', 'Storage'), ('case', 'Case'), ('cooler', 'Cooler'), ('fan', 'Case Fan')], max_length=20),
        ),
    ]
